version: '3'

services:
  app:
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app
    depends_on:
      - db
  db:
    image: sqlite:debian
    volumes:
     - ./dev.db:/var/lib/sqlite/db/dev.db